# Generated by Django 2.2.4 on 2021-05-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='Headline',
        ),
    ]
